# Generated by Django 5.2.8 on 2025-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=50),
        ),
    ]
