# Generated by Django 5.2.8 on 2025-11-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Especialidade", "0001_initial"),
        ("Medico", "0002_alter_medico_especialidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="especialidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Especialidade.especialidade",
            ),
        ),
    ]
