# Generated by Django 5.2.8 on 2025-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
