# Generated by Django 5.2.8 on 2025-11-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Medicamento", "0001_initial"),
        ("Receita", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceitaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Medicamento.medicamento",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Receita.receita",
                    ),
                ),
            ],
        ),
    ]
